### ISSUE TITLE
creating pancake swap with own deployed factory and router, json rpc error

### ISSUE THREAD

**Issue by PnW1** [pancakeswap/pancake-swap-sdk#11]
![Screenshot_2](https://user-images.githubusercontent.com/70314412/141253148-1eef43e0-1e47-44c8-849c-d333e55d6523.png)
Is it possible to deploy our own router, factory and wbnb, when I am trying with my deployed router, factory and wbnb. it shows me json rpc error code 32000 message execution reverted. or I have to use the router and factory which are deployed by pancake swap

**Comment by Chef-Cheems** [comment]
Hi! Sorry for late reply.
It should be possible. Make sure you modified all constants in here to match your deployment.
