### ISSUE TITLE
The value returned by Price does not match the value displayed on the PancakeSwap swap screen.

### ISSUE THREAD

**Issue by Kate-AC** [pancakeswap/pancake-swap-sdk#35]
Hello.
Here is an example.

```js
  const token0 = await Fetcher.fetchTokenData(56, '0x3019BF2a2eF8040C242C9a4c5c4BD4C81678b2A1', bscProvider, 'GMT');
  const token1 = await Fetcher.fetchTokenData(56, '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56', bscProvider, 'BUSD');
  const pair = await Fetcher.fetchPairData(token0, token1, bscProvider);

  console.log(pair.token0Price.toSignificant(6)); // GMT price
  console.log(pair.token1Price.toSignificant(6)); // BUSD price
```

These GMT and BUSD prices do not match the values shown on the PancakeSwap swap screen. 
(The discrepancy is large for an error due to execution timing).
I am assuming that the "GMT value at 1BUSD" and "BUSD value at 1GMT" are calculated respectively, is that wrong?
If I am wrong, what should I use to display the exchange rate similar to the PancakeSwap swap screen?

**Comment by chef-jojo** [comment]
There's not enough liquidity in [CAKE-GMT](https://pancakeswap.finance/info/pool/0x9A21DF205Ca3117D84E44c830385af9bF27ACF6E) pair

You can use [USDC](https://pancakeswap.finance/info/token/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d) to display the exchange rate

If you want to get GMT/BUSD price, `Route` and `Trade` are needed, current best trade route is GMT > BNB > BUSD.

Let me know if you still have questions 🙂  happy hacking
